### ISSUE TITLE
[TureNAS Scale] Need updated Java verision for 1.21 support

### ISSUE THREAD

**Issue by TirantRex** [hexparrot/mineos-node#555]
1.21 currently does not work from the official TrueNAS Scale Charts due to an incompatible java version. Server will not start and produces no logs. The same server running version 1.20.4 works without issue. 

Opening a shell in the MineOS pod and running "java --version" return the following: 
openjdk 17.0.2 2022-01-18
OpenJDK Runtime Environment (build 17.0.2+8-Ubuntu-120.04)
OpenJDK 64-Bit Server VM (build 17.0.2+8-Ubuntu-120.04, mixed mode, sharing)

According to PaperMC's documentation (https://docs.papermc.io/paper/getting-started) 1.21 needs at least Java version 21 to work.

Please let me know if you need any additional information from me as I would like to get this issue resolved soon.

**Comment by false-fox** [comment]
thanks for posting that fix while we wait, appreciate it.

**Comment by SweetMoFo** [comment]
Thanks for this, it nearly worked but I go the error "Unable to locate package openjdk-21-jdk" 

 To solve this I ran "apt update" first then ran "apt-get install openjdk-21-jdk" 

I am on the latest TrueNAS ElectricEel 24.10.0.1 and using the standard MineOS app (not Charts) so this might be why.

**Comment by gmemstr** [comment]
Looks like this should be fixed as of https://github.com/hexparrot/mineos-node/commit/53fb3b7421c2c16528e2a2d2cb991061425d624c

**Comment by Tormak3D** [comment]
It's not fixed because the iso was not update with this commit, @hexparrot can you build a new iso/release with the last commit ?

**Comment by ondra2305** [comment]
Also run into this and yes the dependencies need to be updated, but the bigger issue (in my opinion) is the absolutely no errors or output when trying to start the server, I had to really dig to discover the incompatible Java version was the problem...

**Comment by Engineer152** [comment]
@hexparrot Could you please build the new release for the latest commits? This is still an issue as the java version is stuck on 17
